### ISSUE TITLE
Can't parse crontab

### ISSUE THREAD

**Issue by ipdae** [spoqa/settei#12]
config celery beat using crontab but not work.
```
[worker.celerybeat_schedule.every_midnight]
task = "example.task"
schedule = "crontab(hour='0')"  # midnight
args = []
```

```
celery beat v3.1.23 (Cipater) is starting.
__    -    ... __   -        _
Configuration ->
    . broker -> redis://localhost:6379/0
    . loader -> ads.celery.Loader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%DEBUG
    . maxinterval -> now (0s)
[2016-11-04 08:58:09,529: DEBUG/MainProcess] Setting default socket timeout to 30
[2016-11-04 08:58:09,531: INFO/MainProcess] beat: Starting...
[2016-11-04 08:58:09,534: CRITICAL/MainProcess] beat raised exception <class 'AttributeError'>: AttributeError("'str' object has no attribute 'app'",)
Traceback (most recent call last):
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/kombu/utils/__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 470, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/kombu/utils/__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 512, in scheduler
    return self.get_scheduler()
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 507, in get_scheduler
    lazy=lazy)
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 358, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 185, in __init__
    self.setup_schedule()
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 421, in setup_schedule
    self.merge_inplace(self.app.conf.CELERYBEAT_SCHEDULE)
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 313, in merge_inplace
    entry = self.Entry(**dict(b[key], name=key, app=self.app))
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/beat.py", line 93, in __init__
    self.schedule = maybe_schedule(schedule, relative, app=self.app)
  File "/Users/ung/.venvs/ads/lib/python3.5/site-packages/celery/schedules.py", line 592, in maybe_schedule
    s.app = app
AttributeError: 'str' object has no attribute 'app'
```

**Comment by ipdae** [comment]
이거 소스코드를 뜯어보니까 `settei/presets/celery.py` 파일이 저장소파일이랑 다르네요. 재설치를 해도 그런거보면 pypi에 릴리즈된 버전이랑 저장소에 차이가 있어서 터지는 에러같습니다.

**Comment by kanghyojun** [comment]
0.2.2 릴리즈하려고 버전까지올렸는데 정작 제가 메인테이너가아니네요. @dahlia @Kroisse 메인테이너에 저도 넣어주실수있나요?

**Comment by dahlia** [comment]
@admire93 넣으려고 하니까 PyPI의 인증 기능 버그(pypa/pypi-legacy#258)로 role 추가가 안되네요. 대신 제가 업로드했습니다:

https://pypi.python.org/pypi/settei/0.2.2

근데 올려놓고 보니까 0.2.1은 릴리스한 적이 없는데 0.2.0에서 바로 0.2.2로 올라갔네요. 왜 그런지 알 수는 없지만 `long_description`도 안 채워져 있고…

**Comment by kanghyojun** [comment]
0.2.1 을 릴리즈안한모양이군요 ㅋㅋ  일단 이 이슈는 릴리즈로 해결된거같습니다.
