### ISSUE TITLE
tsukkomi TypeError in 3.6

### ISSUE THREAD

**Issue by ygzgxyz** [spoqa/settei#14]
```python
>>> class Conf(settei.Configuration):
...     a = settei.config_property('a.debug', bool, default=False)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in Conf
  File "/Users/khj/.pyenv/versions/test/lib/python3.6/site-packages/tsukkomi/typed.py", line 220, in decorator
    check_arguments(call_, hints, *args, **kwargs)
  File "/Users/khj/.pyenv/versions/test/lib/python3.6/site-packages/tsukkomi/typed.py", line 182, in check_arguments
    actual_type, correct = check_type(value, type_hint)
  File "/Users/khj/.pyenv/versions/test/lib/python3.6/site-packages/tsukkomi/typed.py", line 46, in check_type
    elif issubclass(hint, typing.Union):
  File "/Users/khj/.pyenv/versions/3.6.0/lib/python3.6/typing.py", line 770, in __subclasscheck__
    raise TypeError("Unions cannot be used with issubclass().")
TypeError: Unions cannot be used with issubclass().
```

Environment:
```bash
$ python --version
Python 3.6.0
$ pip freeze | grep -i settei
settei==0.2.2
```

**Comment by dahlia** [comment]
Could you determine what version of tsukkomi you're using (`pip freeze | grep tsukkomi`)?

**Comment by ygzgxyz** [comment]
@dahlia : 0.0.6 and it seems that it's latest release in PyPI.

**Comment by kanghyojun** [comment]
i created an issue  (https://github.com/spoqa/tsukkomi/issues/16)

**Comment by dahlia** [comment]
We replaced tsukkomi with [typeguard][1] since [Settei 0.3.0][2].

[1]: https://github.com/agronholm/typeguard
[2]: https://settei.readthedocs.io/en/latest/changes.html#version-0-3-0
